### ISSUE TITLE
Download Thunderbird header button is not really downloading anything

### ISSUE THREAD

**Issue by Alecaddd** [thunderbird/thunderblog#27]
The Download Button in the header area redirects to the website, which is misleading and not correct.
Also, we currently don't have any easy indication on "how to go to the main website" from the blog.

I'd suggest changing that button to "Get Thunderbird". More generic, and a somewhat good entry point to go to the website.
@ryanleesipes, thoughts?

**Comment by ryanleesipes** [comment]
Agreed. I'll change it.

**Comment by MelissaAutumn** [comment]
@Alecaddd Does this still need to be changed?
