### ISSUE TITLE
Add "Share to Mastodon" button 

### ISSUE THREAD

**Issue by KillYourFM** [thunderbird/thunderblog#45]
Add a "Share to Mastodon" button to the existing share toolbar underneath blog posts. 

[This guide](https://www.kylereddoch.me/2023/02/20/creating-mastodon-share-button.html) may be helpful.

**Comment by CubeOfCheese** [comment]
I was looking into the options for doing this. Here's what I found:

This option already mentioned above:
https://www.kylereddoch.me/2023/02/20/creating-mastodon-share-button.html

http://grayleonard.com/mastodon-share/demo.html

Third party service that provides a instance-agnostic share page: https://toot.kytta.dev/
This seems pretty nice in terms of UX, but for stability, I imagine Thunderbird would want to host its own copy. If we could get this page added to the blog though, I think it offers the best experience out of the options presented.

**Comment by CubeOfCheese** [comment]
On second look, the toot.kytta.dev option doesn't seem viable as it runs on node and I now see that this is a wordpress based blog.

**Comment by CubeOfCheese** [comment]
Okay I have a new favorite to recommend:
https://github.com/Juerd/tootpick
This is a very similar implementation to toot.kytta.dev but can be self hosted as a single self-contained html page. I imagine this should be achievable fairly simply in wordpress.
I think the design of the page could use a little touching up - maybe style it to match thunderbird's theme and style, but other than that I think this would be a great way to add a share to mastodon button.

**Comment by KillYourFM** [comment]
@MelissaAutumn Do any of the above seem like viable options to implement in the near future?

**Comment by MelissaAutumn** [comment]
I've seen tootpick used in other places directly, so that's definitely an option!

Although I actually prefer @micahilbery's web component the most. Integration would be pretty simple as it's just a javascript web component, and it's also extremely easy on the eyes. The only problem here is we're missing a mastodon share icon. 😄

<img width="803" alt="image" src="https://github.com/thunderbird/thunderblog/assets/97147377/6387be44-2f13-4161-b3c6-731dc268b1de">

https://github.com/micahilbery/share-on-mastodon/

**Comment by KillYourFM** [comment]
HA! I actually used that share functionality last week and didn't even realize it was Micah's. 
Mastodon doesn't seem to have any official "Share" icons, so I suppose we need to roll our own using their [brand guidelines](https://joinmastodon.org/branding)?

**Comment by MelissaAutumn** [comment]
Yep, if we can get an icon similar to our existing portfolio here:
<img width="552" alt="image" src="https://github.com/thunderbird/thunderblog/assets/97147377/3f0795e7-04d7-4ca6-a372-eb05f20a6f87">

Then I or someone else can slot it right in.

**Comment by devmount** [comment]
I used [Tabler icons](https://tabler.io/icons) for those, so you just need the following SVG:

```html
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-m" viewBox="0 0 24 24">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M18.648 15.254c-1.816 1.763 -6.648 1.626 -6.648 1.626a18.262 18.262 0 0 1 -3.288 -.256c1.127 1.985 4.12 2.81 8.982 2.475c-1.945 2.013 -13.598 5.257 -13.668 -7.636l-.026 -1.154c0 -3.036 .023 -4.115 1.352 -5.633c1.671 -1.91 6.648 -1.666 6.648 -1.666s4.977 -.243 6.648 1.667c1.329 1.518 1.352 2.597 1.352 5.633s-.456 4.074 -1.352 4.944z" /><path d="M12 11.204v-2.926c0 -1.258 -.895 -2.278 -2 -2.278s-2 1.02 -2 2.278v4.722m4 -4.722c0 -1.258 .895 -2.278 2 -2.278s2 1.02 2 2.278v4.722" />
</svg>
```

I can take a look in the upcoming days.

**Comment by micahilbery** [comment]
I'm definitely willing to take PRs upstream if there is anything you'd like that would make it more extendable and versatile. Also if you see anything I'm doing wrong or could do better I'm all for the corrections too. It was the first web-component (and only, so far) that I've written so I'm sure there's room for improvement.

**Comment by MelissaAutumn** [comment]
I think if we wrap the inner contents of mastodonBtn with a slot element, we can easily override the existing button with our svg, while still preserving the default button if theres no child data in the web component element.

That's how I'd probably do it.

**Comment by devmount** [comment]
@micahilbery Thank you for merging the PR 👏🏻 Do you mind releasing and publishing the next version (1.0.6? 1.1.0?) on npm?

**Comment by micahilbery** [comment]
> @micahilbery Thank you for merging the PR 👏🏻 Do you mind releasing and publishing the next version (1.0.6? 1.1.0?) on npm?

@devmount I learned a lot today 😅 but I think I finally got it published and setup with GitHub Actions so hopefully it will remain up-to-date.

**Comment by MelissaAutumn** [comment]
Just a small comment, we might want to grid the share icons. On my phone (Galaxy Flip Z 5) whoch is pretty narrow the icons are cut off. ![Screenshot_20240130_095145_Firefox.jpg](https://github.com/thunderbird/thunderblog/assets/97147377/29a16a0b-7e24-4143-9570-856976e86f5c)

**Comment by devmount** [comment]
Thanks to both of you, will fix that on the way.

**Comment by devmount** [comment]
@MelissaAutumn What do you think would be the best implementation strategy here? Since this is a simple WP theme, we don't have a build step (and I still don't think we need it). So that leaves us with the following option:

1. Use a script tag and call jsdelivr.net on every request
2. Use the web component as git submodule

**Comment by devmount** [comment]
Ok I went with the first option for now in #46. We can improve that later if there's need.

**Comment by MelissaAutumn** [comment]
We should actually pull in the script file into our repo. Submodules would complicate things, and remote calls can be slow/blocking or eventually lead to security concerns. 

It does mean we'll have to update the script anytime Micah does a release, but it seems like a pretty feature complete component right now so I'm not too worried about that.

**Comment by devmount** [comment]
Alright, I'll add that script file to our assets then. Will update this PR in a few

**Comment by MelissaAutumn** [comment]
This is now live!
