### ISSUE TITLE
Support display of multiple author for a single post

### ISSUE THREAD

**Issue by babolivier** [thunderbird/thunderblog#50]
When a post has several authors (for example https://blog.thunderbird.net/2024/04/adventures-in-rust-bringing-exchange-support-to-thunderbird/), the blog only shows one of them, despite WordPress seemingly registering all relevant users as authors (which can be verified by looking at the value for the `meta name="author"` tag).

**Comment by devmount** [comment]
Good catch, I'll take a look at that. Thanks

**Comment by devmount** [comment]
Implemented this in #51. Needs to be deployed (@MelissaAutumn)

**Comment by MelissaAutumn** [comment]
Resolved in the latest release: https://github.com/thunderbird/thunderblog/releases/tag/v1.0.15

This will be deployed shortly.
