### ISSUE TITLE
Large empty space underneath the Thunderbird logo in the blog's footer

### ISSUE THREAD

**Issue by babolivier** [thunderbird/thunderblog#57]
This is what I currently see when I scroll down to the blog's footer, both authenticated and unauthenticated:

![image](https://github.com/thunderbird/thunderblog/assets/5547783/e6b7c1d1-4a6f-4f46-aba5-868649a45ddb)

From the size of the empty space, and also the HTML that's in there, it looks very much like there should be _something_ that isn't rendering properly. #53 makes me think this suspicion might be true.

This persists after a cache clear, and even in private browsing. I'm running latest Firefox (125.0.X), and I've observed this on both Windows and Arch Linux.

I'm happy to provide any more detail that could be helpful and I might not have thought of :)

**Comment by devmount** [comment]
Hi Brendan, you're totally right. This isn't really a bug, the content team simply didn't decide yet, what to put there. Here is what it was supposed to look like when I created the mockups:

https://github.com/thunderbird/thunderblog/issues/25#issuecomment-1329642064

Marking this as duplicate, but thanks anyway for this report!
