### ISSUE TITLE
Enable "Full Width" on YouTube embeds

### ISSUE THREAD

**Issue by KillYourFM** [thunderbird/thunderblog#60]
Wordpress supports YouTube embeds, along with multiple alignment settings for those code blocks. 
Currently, the only alignment options are "left / center / right." We need to have "Full Width" enabled so that video embeds will consume the full width of the page and scale accordingly, similar to how images behave. 

Wordpress documentation [says](https://wordpress.org/documentation/article/youtube-embed/) this needs to be enabled on the Theme level. 

Current example in CMS: 

![image](https://github.com/thunderbird/thunderblog/assets/47599547/1397887d-f234-4e54-9ddf-47988da4154b)

Output on published blog: 

![image](https://github.com/thunderbird/thunderblog/assets/47599547/7c7ec688-9d5a-4fbf-bdfd-775c71d6e824)

**Comment by devmount** [comment]
Yes, I'll take a look at that tomorrow

**Comment by devmount** [comment]
Hi Jason, I added support for full-width embeds in #63. Once that is merged and released, you can set the newly available block options for align-wide or align-full, which both will make the youtube embed as wide as the surrounding text.
