### ISSUE TITLE
Header logo appears gigantic on Firefox 115

### ISSUE THREAD

**Issue by LinuxForEveryone** [thunderbird/thunderblog#64]
**Environment: Arch Linux, Firefox ESR (115.112.0esr)**

When viewing all pages at https://blog.thunderbird.net with Firefox ESR, the "Thunderbird Logo" appears gigantic. 

![image](https://github.com/thunderbird/thunderblog/assets/47599547/2f9ea15e-4f60-489e-af4a-0de28a5c9332)

However, it looks perfect in Firefox 127. 

@inattee also noticed it may be borked in older versions of Chrome:

![image](https://github.com/thunderbird/thunderblog/assets/47599547/15983358-f640-4230-a358-82062b53417f)

If you need any other technical details, let me know.

**Comment by devmount** [comment]
Oh wow, thanks for the report. I'll investigate.

**Comment by devmount** [comment]
Looks like CSS nesting is responsible (https://caniuse.com/css-nesting). I provided a fix.

**Comment by MelissaAutumn** [comment]
We can re-visit nesting once Firefox 115 is deprecated. I don't think we should care about old versions of chrome tbh.
